default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: reuyhgxjraom3q84tciu
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: DBName_Development

test:
  <<: *default
  database: DBName_Test

production:
  <<: *default
  database: DBName_Production
  username: postgres
  password: reuyhgxjraom3q84tciu